### ISSUE TITLE
Resetando o CSS

### ISSUE THREAD

**Issue by tayhsn** [MellonFive/Desafio-CSS#2]
Você não precisa ter um arquivo como o reset.css no seu projeto, o que você usa é mais pra ilustração, mas na prática é melhor você usar: 

 '*' (o asterisco significa TUDO) {
 margin: 0px
padding: 0px
--- o básico ---
E adiciona o que fizer sentido ao seu projeto, como por exemplo:
Box-sizing: border-box
Text-decoration: none

Font-family, font-size.....
}

Essa é só uma dica pra sua arquitetura ficar enxuta e você utilizar o que mais fácil sentido ao seu projeto (é um diferencial principalmente quando você estiver submetendo a teste técnico)

**Comment by tayhsn** [comment]
Percebi também que você tem um arquivo CSS para cada elemento, isso também não eh uma boa escolha de arquitetura. O ideal eh que você tenha um arquivo global que contenha os estilos que você pode reaproveitar em mais de uma página, e o arquivo de cada página respectiva, no seu caso index.css e resultado.css contendo os estilos específicos de cada html

**Comment by MellonFive** [comment]
Olá tudo bem @tayhsn ? Aprendi a fazer dessa forma em um curso do marco bruno dev, um curso pago. Ainda não aprendi de outras formas. Desse jeito com essa arquitetura, dá mais fácil acesso a manutenção de códigos CSS. 
Observe esse curso que estou fazendo: https://github.com/MellonFive/loja-fone2 . É um curso da collabcode, não sei se você já ouviu falar. Observe a arquitetura, como ela é bem organizada. O reset.css são para projetos pequenos. Se eu usar de forma global(*) pode dar erros futuros. Se eu fizer tudo em um único arquivo CSS(style.css) fico perdido na hora de dar manutenção.
Agradeço pelo seus comentários.

**Comment by tayhsn** [comment]
Ah entendi. Bom, meu comentário é por que essas formas não são utilizadas no mercado e projetos maiores, mas se você está aprendendo e essa forma te ajuda, continue nela 🤝

**Comment by MellonFive** [comment]
Opa, bom dia! É uma pena que dessa forma não é aceito no mercado de trabalho. É melhor assim do que ter um único arquivo CSS(style.css). Sempre pense em refatoração(Codar para os outros). Quanto mais arquivos CSS organizados, melhor para refatorar e dar manutenção.
Abraços.

**Comment by tayhsn** [comment]
Digo o mesmo: sempre pense em refatoração e em deixar seu código claro para qualquer pessoa, inclusive você no futuro. Não é uma pena o mercado preferir assim, o mercado nada mais é que todos os desenvolvedores que atuam nele. Os padrões de projeto (ali em cima eu falei arquitetura erroneamente, sorry) é feito por profissionais da área. 

O melhor que eu posso te dizer é para procurar ver como outros profissionais desenvolvem, para que você não fique sempre preso a uma forma muito inicial de codificação. 

Enfim, sucesso!
